@baseUrl = https://api.comppare.com.br/api
#@baseUrl = http://127.0.0.1:8000/api
### GET request para testar a api
GET {{baseUrl}}/test

#usuarios
###cadastrar
POST {{baseUrl}}/usuarios/cadastrar
Content-Type: application/json

{
    "primeiroNome": "Luis",
    "sobrenome": "Pimenta",
    "apelido": "luispimenta95",
    "cpf": "02049035055",
    "senha": "Mp13151319!",
    "telefone": "61998690313",
    "email": "luispimenta.contato@gmail.com",
    "idPlano": 1,
    "nascimento": "19/09/1995"
}


###listar
GET {{baseUrl}}/admin/usuarios/listar


###Autenticar
POST {{baseUrl}}/usuarios/autenticar
Content-Type: application/json

{
    "cpf": "02049035055",
    "senha": "13151319"
}

###recuperar
POST {{baseUrl}}/usuarios/recuperar
Content-Type: application/json

{
    "idUsuario": 3
}

###checarExistencia
POST {{baseUrl}}/usuarios/valida-existencia-usuario
Content-Type: application/json

{
    "cpf": "42708782070"
}

###atualizar senha
POST {{baseUrl}}/usuarios/atualizar-senha
Content-Type: application/json

{
    "cpf": "42708782070",
    "senha": "123"
}


###Requests planos

###cadastrarPlanos
POST {{baseUrl}}/planos/cadastrar
Content-Type: application/json

{
    "nome": "Teste plano EFI",
    "descricao": "Teste",
    "valor": 1,
    "quantidadeTags": 1,
    "quantidadeFotos": 1,
    "quantidadePastas": 1,
    "online": true,
    "frequenciaCobranca": 12

}


###recuperar
POST {{baseUrl}}/planos/recuperar
Content-Type: application/json

{
    "idPlano" : 3
}

###listar
GET {{baseUrl}}/planos/listar


##Cupons
###recuperar
POST {{baseUrl}}/cupons/recuperar
Content-Type: application/json

{
    "idCupom" : 3
}

###listar
GET {{baseUrl}}/cupons/listar

###Cadastro de cupons

POST {{baseUrl}}/cupons/cadastrar
Content-Type: application/json

{
    "cupom": "Teste",
    "percentualDesconto": 10,
    "quantidadeDias": 5
}

###assinatura
POST {{baseUrl}}/vendas/criar-assinatura
Content-Type: application/json

{
    "usuario":1,
    "plano": 1,
    "valor": 39.9,
    "token": "acvvcyt"
}


###CANCELAR ASSINATURA

POST {{baseUrl}}/vendas/cancelar-assinatura
Content-Type: application/json

{
    "usuario":8
}


###pastas
###cadastrar
POST {{baseUrl}}/pasta/create
Content-Type: application/json
#Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwczovL2FwaS5jb21wcGFyZS5jb20uYnIvYXBpL3VzdWFyaW9zL2F1dGVudGljYXIiLCJpYXQiOjE3NDgyMTc3MzEsImV4cCI6MTc0ODIyMTMzMSwibmJmIjoxNzQ4MjE3NzMxLCJqdGkiOiJncHhlN2NsRUxNaXRYdVdvIiwic3ViIjoiMiIsInBydiI6IjU1NGM1YWVhNGNiMjU0MDE5ZTEyMDY3YTdjYTU0N2Y2NzVkNTQ0Y2EifQ.m6rWAD_GHVs-GDWIvlH_yBMCI4QO3VSH0BYF09fiZTE

{
    "idUsuario": 2,
    "nomePasta": "pimenta/upload0"
}

###excluir pasta
DELETE {{baseUrl}}/pasta/delete
Content-Type: application/json

{
    "idUsuario": 2,
    "idPasta": 40
}

###ranking
###cadastrar
POST {{baseUrl}}/ranking/atualizar
Content-Type: application/json

{
"pontos": 10,
 "usuario": 1
}


###atualizar plano
POST {{baseUrl}}/api/usuarios/atualizar-plano
Content-Type: application/json
Authorization: Bearer 123

{
    "cpf": "81581828012",
    "plano": 5
}


###esqueci senha
POST {{baseUrl}}/usuarios/esqueceu-senha
Content-Type: application/json  

{
    "email": "teste@gmail.com"
}

###imagens
###excluir imagem
DELETE {{baseUrl}}/imagens/excluir
Content-Type: application/json

{
    "idUsuario": 2,
    "idPhoto": 15
}

###excluir pasta
DELETE {{baseUrl}}/pasta/excluir
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwczovL2FwaS5jb21wcGFyZS5jb20uYnIvYXBpL3VzdWFyaW9zL2F1dGVudGljYXIiLCJpYXQiOjE3NDgyMTc3MzEsImV4cCI6MTc0ODIyMTMzMSwibmJmIjoxNzQ4MjE3NzMxLCJqdGkiOiJncHhlN2NsRUxNaXRYdVdvIiwic3ViIjoiMiIsInBydiI6IjU1NGM1YWVhNGNiMjU0MDE5ZTEyMDY3YTdjYTU0N2Y2NzVkNTQ0Y2EifQ.m6rWAD_GHVs-GDWIvlH_yBMCI4QO3VSH0BYF09fiZTE

{
    "idUsuario": 2,
    "idPasta": 40
}

###recuperar pasta individual
GET {{baseUrl}}/pasta/recuperar?idPasta=26
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwczovL2FwaS5jb21wcGFyZS5jb20uYnIvYXBpL3VzdWFyaW9zL2F1dGVudGljYXIiLCJpYXQiOjE3NTI2MTkxMDIsImV4cCI6MTc1MjYyMjcwMiwibmJmIjoxNzUyNjE5MTAyLCJqdGkiOiJqQmdSV0poS2pncE43S29TIiwic3ViIjoiMSIsInBydiI6IjU1NGM1YWVhNGNiMjU0MDE5ZTEyMDY3YTdjYTU0N2Y2NzVkNTQ0Y2EifQ.X36IgXm8avWayQytb4Z2u94NoElPP-s8xbDb8VOccQI
