#@baseUrl = https://api.comppare.com.br/api
@baseUrl = http://127.0.0.1:8000/api
### GET request para testar a api
GET {{baseUrl}}/test

#usuarios
###cadastrar
POST {{baseUrl}}/usuarios/cadastrar
Content-Type: application/json

{
    "nome": "Luis Pimenta",
    "cpf": "01234567890",
    "senha": "13151319",
    "telefone": "61998690313",
    "email": "luispimenta.contato@gmail.com",
    "idPlano": 1,
    "idPerfil": 2,
    "nascimento": "19/09/1995",
    "cardToken": "0a9fc512fa67d3a9a217a1c34be522e878a2baa7"
}


###listar
GET {{baseUrl}}/usuarios/listar


###Autenticar
POST {{baseUrl}}/usuarios/autenticar
Content-Type: application/json

{
    "cpf": "02342288140",
    "senha": "13151319"
}

###recuperar
POST {{baseUrl}}/usuarios/recuperar
Content-Type: application/json

{
    "idUsuario": 3
}

###checarExistencia
POST {{baseUrl}}/usuarios/valida-existencia-usuario
Content-Type: application/json

{
    "cpf": "42708782070"
}

###atualizar senha
POST {{baseUrl}}/usuarios/atualizar-senha
Content-Type: application/json

{
    "cpf": "42708782070",
    "senha": "123"
}


###Requests planos

###cadastrarPlanos
POST {{baseUrl}}/planos/cadastrar
Content-Type: application/json

{
    "nome": "Teste plano EFI",
    "descricao": "Teste",
    "valor": 45,
    "quantidadeTags": 1,
    "quantidadeFotos": 1,
    "quantidadePastas": 1

}


###recuperar
POST {{baseUrl}}/planos/recuperar
Content-Type: application/json

{
    "idPlano" : 3
}

###listar
GET {{baseUrl}}/planos/listar


##Cupons
###recuperar
POST {{baseUrl}}/cupons/recuperar
Content-Type: application/json

{
    "idCupom" : 3
}

###listar
GET {{baseUrl}}/cupons/listar

###Cadastro de cupons

POST {{baseUrl}}/cupons/cadastrar
Content-Type: application/json

{
    "cupom": "Teste",
    "percentualDesconto": 1
}


