name: Laravel Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Set up PHP environment
      - name: Setup PHP
        uses: shivammathur/setup-php@v3
        with:
          php-version: '8.2' # Preferred PHP version
          extensions: mbstring, bcmath, pdo, tokenizer
          coverage: none

      # Step 3: Install dependencies
      - name: Install Composer Dependencies
        run: composer install --no-progress --no-suggest --optimize-autoloader

      # Step 4: Update .env file (adjust as necessary)
      - name: Prepare Environment
        run: |
          cp .env.example .env
          php artisan config:clear
          php artisan config:cache

      # Step 5: Run Laravel commands
      - name: Clear and Optimize
        run: |
          php artisan cache:clear
          php artisan route:clear
          php artisan route:cache
          php artisan view:clear
          php artisan view:cache
          php artisan optimize

      - name: Run Migrations
        run: php artisan migrate --force

      # Optional: If you need to restart queues, include this
      - name: Restart Queues
        run: php artisan queue:restart
